packages:
  - "projects/packages/*"
minimumReleaseAgeExclude:
  - '@doki-land/fractal-darwin-arm64@0.0.2'
  - '@doki-land/fractal-linux-x64@0.0.2'
  - '@doki-land/fractal-unknown-wasm32@0.0.2'
  - '@doki-land/fractal-win32-x64@0.0.2'
  - '@doki-land/fractal@0.0.2'
