[package]
name = "fractal"
publish = false
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "Lindenmayer / turtle fractal core (string rewrite + path)"
repository = "https://github.com/oovm/fractal-art"
readme = "../../../Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]

[dev-dependencies]

[features]
default = []
