[package]
name = "lsystem"
publish = false
version = "0.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "Lindenmayer system string rewriting"
repository = "https://github.com/oovm/LSystem"
readme = "../../../Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]

[dev-dependencies]

[features]
default = []
